services:
  backend:
    build: .
    container_name: enmedio_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:16
    container_name: prueba_enmedio_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/databases:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:7
    container_name: prueba_enmedio_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
